### ISSUE TITLE
Compatibility with rpm-ostree?

### ISSUE THREAD

**Issue by gluckgluckwasserbauch** [Vanilla-OS/core-image#32]
### Feature Description

Make Fedora Silverblue compatible with VanillaOS 2 and allow rebasing from one to another.

### Rationale

Both use ghcr OCI images (from Orchid on), and on Fedora Atomic, you can freely rebase from Silverblue (Gnome) to Kinoite (KDE) to uBlue (custom spins) to Bazzite (gaming-distro).

### Additional Information

Maybe I'm super dumb and have no clue how different both are.  
I like the concept of VOS a lot, and maybe, Fedora Atomic and VOS are cross-compatible due to their immutable nature.

**Comment by axtloss** [comment]
I dont see how that would be helpful. rpm-ostree, as the name suggests, uses rpm, which is not compatible with dpkg, the package system vanilla uses. You are technically able to build a fedora based image using vib. But cross compatibility between abroot and rpm-ostree isn't helpful for users or worth the effort.
